services:
  rabbitmq:
    image: rabbitmq:management
    hostname: localhost
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
